name: RunTests
# Runs the workflow on the below events:
# 1. on pull request raised to trunk branch.
# 2. on push event to trunk branch.
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  lint-markdown:
    runs-on: ubuntu-20.04
    name: Run Tests
    steps:
      - name: checkout repo content
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install MicroPython and run tests
        run: |
          DLURL="https://github.com/atsign-foundation/micropython/releases/download/"
          ATMPRELDIR="1.22.0_g099e9a1a0_AES_CTR/"
          ATMPRELBIN="micropython_1.22.0_g099e9a1a0_linux_x64.tgz"
          wget ${DLURL}${ATMPRELDIR}${ATMPRELBIN}
          tar -xvf ${ATMPRELBIN}
          export MICROPY_MICROPYTHON="$(pwd)/micropython"
          cd tests
          ./run-tests.py -d atsign
          tar -cvzf results.tgz results
      - name: Upload results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: atsign tests
          path: tests/results.tgz
          retention-days: 7

